### ISSUE TITLE
Restrict exact base classes.

### ISSUE THREAD

**Issue by proofit404** [adamchainz/pytest-restrict#121]
Hi, thanks for the awesome project.

Let say I want to allow writing of unit tests based on `unittest.TestCase`. But at the same time, I want to restrict my integration tests to use `MyAdvancedTestCase(django.test.TestCase)`.

If I include `unittest.TestCase` into `--restrict-types` list, it'll allows `django.test.TestCase` as a valid base class.

Maybe there is an ability to include `--restrict-exactly` flag?

Have a good day :tada: 

Best regards,
Artem.

**Comment by adamchainz** [comment]
Hi

I don't think there's much value in restricting so heavily. Asides from maintaining your unit/integration split, you'd also be banning *any* common subclasses for your tests, which I've always found useful to create in larger projects to share extra assertions, setup, etc.

A different approach would be to define `MyUnitTestCase(unittest.TestCase)` and then restrict to `MyUnitTestCase` and `MyAdvancedTestCase`. This would hold the guarantee for you that `django.test.SimpleTestCase` etc. aren't directly in use, which sounds like the main thing you'd want to restrict.

Thanks,

Adam

**Comment by proofit404** [comment]
Makes sense. Thanks!
